[project]
name = "TranscodeTycoonGame"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "numpy>=2.3.2",
    "toml>=0.10.2",
    "uvicorn>=0.35.0",
]
